### PR TITLE
Adds context and example/complete

### PR DESCRIPTION
**Pull request by lezavala**
## what
* Adds context.tf
* Adds example/complete.

## why
* Attempt to add a decent test and bring repo up to standards.

### CODE REVIEW

**Comment by aknysh** [comment]
@lezavala  thanks for the PR.
Could you please run the following commands:

```
make init
make github/init
make readme
```

This will bring in all the latest GitHub actions we are adding to all modules.

Thank you

**Comment by aknysh** [comment]
@lezavala 
thanks a lot for the updates.
Everything looks good now, except for some reason README was not updated.
Also, TF code needs to be formatted in the module and in the example.

We usually execute ChatOps commands as comments on PRs to rebuild README and format TF code, but it looks like our bot does not have access to your repo (there is some protection).

Can you please execute these commands again:

```
make init
make readme
```

and also `terraform fmt` on the module and on the example.

Thank you

**Comment by lezavala** [comment]
> Also, TF code needs to be formatted in the module and in the example.
> 
> ...and also `terraform fmt` on the module and on the example.
> 

Not sure how to

**Comment by lezavala** [comment]
Accidentally closed this

**Comment by aknysh** [comment]
@lezavala 
new release with all your changes https://github.com/cloudposse/terraform-aws-sns-lambda-notify-slack/releases/tag/0.5.0

**Pull request merged**
