### PR TITLE
Update terraform aws notify slack version

### PR DESCRIPTION
**Pull request by wittro**
Hi, I'd like to resolve a warning like below lines appearing in my terraform both of plan and apply.

```bash
  on .terraform/modules/xxx.notify_slack/main.tf line 107, in resource "aws_lambda_function" "notify_slack":
 107:   depends_on = ["aws_cloudwatch_log_group.lambda"]
```

This causes from old version terraform-aws-notify-slack so I bump up it in this repository from v2.3.0 to latest one.

### CODE REVIEW

**Comment by wittro** [comment]
@aknysh 
Hi, I would be really grateful if you could check on this.

**Comment by wittro** [comment]
@maximmi 
Although I can't see the test status of codefresh, is there anything I can do for merging this PR?

**Comment by razorsedge** [comment]
Can someone explain what is holding up this PR's merge?

**Comment by Gowiem** [comment]
@razorsedge We have a policy that we can't merge without all tests passing. Seems this module sat for a bit and the tests broke so we need to have somebody from the contributor team or community come along and fix them before this or the other 3 PRs that are outstanding can get merged. It's painful, but Cloud Posse has 200 or so TF modules, so it needs to be done. 

Take a crack at fixing the tests if you get the chance and we can get this merged!

**Comment by wittro** [comment]
ah, I'll try to fix it later.

**Pull request closed without merging**
